### ISSUE TITLE
Authenticator.class: Only WebAuthenticator works

### ISSUE THREAD

**Issue by wsdt** [Clancey/simple_auth#64]
When logging in with correct credentials we get redirected as expected to our redirect uri. 
Unfortunately, only the InstagramApi closes the window and we receive the token etc. 

Facebook, Github, and all other do not close the window as those Authenticator-childs do not respond. 

So, when closing the browser window we get the Cancelled Exception message. 
As we saw this issue in another issue: Our user, api credentials and the redirect uris are correct so that might not be the cause. 

Thank you in advance :)

**Comment by Clancey** [comment]
This is fixed by using a custom scheme to redirect and registering it in the application.manifest.  https://github.com/Clancey/simple_auth#redirect

**Comment by wsdt** [comment]
Unfortunately, it is not. We used a **local** redirect link. In that case the redirection worked in every case (except for Google and this might/will be resolved by adding it to the manifest). 

But as said the redirection for all other apis worked, just the window did not close which then resulted in a cancelledexception although the authentication worked out.

**Comment by Clancey** [comment]
Do you mind sharing the redirect url you choose? When you say local, was it localhost?

**Comment by wsdt** [comment]
localhost:8080/redirect

And it worked after authentication. 
It's just the window from the other authenticator classes which does not close automatically

**Comment by Clancey** [comment]
This is exactly what I was thinking. With the secure native logins, it is impossible to redirect that back to the app. As I said before that login window if your not using embedded is outside the scope of your app. So you need a redirect that open the app back up.  I promise you it's worth it to jump through the extra hoops.

you need a custom redirect instead of an http one. Then you need to register it with the application.manifest.  So I would redirect to something like ```myappname://redirect```

Then it will work without the changes your posted. And It is more secure!

**Comment by wsdt** [comment]
Ok I will give it a try!
Thank you for your patience 👍
