### ISSUE TITLE
Custom Scheme/Redirect

### ISSUE THREAD

**Issue by vferreirati** [Clancey/simple_auth#81]
Been trying to use this for a while now. While the authentication works fine, i can't for the life of me get the plugin to close itself after the authentication works. 
Maybe this is a problem related to how my app works

I'm redirecting the user to my rest api after then authentication is made, instead of saving the tokens and refresh tokens on the device.
Something like this: User logs in using his credentials, browser is redirected to my rest api, api saves the token and gives me a basic json response.

What can i do so the browser closes itself when receiving the response from my api?

**Comment by Clancey** [comment]
This is way outside the use case of what SImpleAuth is meant to do, You are better off sending the tokens up from the app, once you receive. The library needs the tokens/refresh in order to know if they are valid, or if it should show the UI.

If you are going to continue down this path, you first are required to redirect back to a custom scheme: https://github.com/Clancey/simple_auth#redirect. Your API can do that, but the UI will not be dismissed until this happens. But once you get past that it is going to have a lot of issues since it will expect tokens it can swap out.
